pygments: true
relative_permalinks: false
gauges_id: 503c5af6613f5d0f19000027


# jekyll config
permalink: /:categories/:title/
exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor", ".htaccess", "index.php"]
include: [""]
pygments: true
lsi: false
auto: false
safe: true